export const INITIAL_MOCK_DATA = {
  users: [
    {
      id: 1,
      username: "admin",
      role: "admin",
      firstName: "System",
      lastName: "Admin",
      email: "admin@bodega.com",
      cedula: "0000000000",
      phone: "555-5555",
      paymentMethod: "Efectivo",
      paymentAmount: 0,
      startDate: new Date().toISOString(),
      cutoffDate: "",
      isActive: true,
    },
    {
      id: 2,
      username: "user",
      role: "user",
      firstName: "Vendedor",
      lastName: "Demo",
      email: "vendedor@bodega.com",
      cedula: "1111111111",
      phone: "555-1234",
      paymentMethod: "Efectivo",
      paymentAmount: 0,
      startDate: new Date().toISOString(),
      cutoffDate: "",
      isActive: true,
    },
  ],
  products: [
    {
      id: 1,
      name: "Arroz 1kg",
      category: "Granos",
      stock: 45,
      minStock: 20,
      price: 1.2,
      cost: 0.8,
      expirationDate: "2025-12-31",
    },
    {
      id: 2,
      name: "Aceite 1L",
      category: "Aceites",
      stock: 8,
      minStock: 10,
      price: 2.5,
      cost: 1.6,
      expirationDate: "2026-06-30",
    },
    {
      id: 3,
      name: "Leche 1L",
      category: "Lácteos",
      stock: 5,
      minStock: 15,
      price: 0.9,
      cost: 0.6,
      expirationDate: "2024-02-15",
    },
    {
      id: 4,
      name: "Atún en lata",
      category: "Conservas",
      stock: 100,
      minStock: 20,
      price: 1.5,
      cost: 1.0,
      expirationDate: "2027-01-01",
    },
    {
      id: 5,
      name: "Yogurt Fresa",
      category: "Lácteos",
      stock: 12,
      minStock: 10,
      price: 0.8,
      cost: 0.55,
      expirationDate: "2024-02-01",
    },
  ],
  movements: [],
  customers: [
    {
      id: 1,
      firstName: "Juan",
      lastName: "Pérez",
      cedula: "12345678",
      phone: "555-1111",
      debt: {
        enabled: true,
        currentDebt: 50,
        daysOverdue: 3,
      },
      createdAt: new Date().toISOString(),
    },
    {
      id: 2,
      firstName: "Ana",
      lastName: "López",
      cedula: "87654321",
      phone: "555-2222",
      debt: {
        enabled: true,
        currentDebt: 120,
        daysOverdue: 12,
      },
      createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    },
    {
      id: 3,
      firstName: "Luis",
      lastName: "Gómez",
      cedula: "11223344",
      phone: "555-3333",
      debt: { enabled: false, currentDebt: 0, daysOverdue: 0 },
      createdAt: new Date(Date.now() - 86400000 * 60).toISOString(),
    },
  ],
  backups: [],
  logs: [
    {
      type: "CREATE",
      message: "Respaldo automático creado",
      ts: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      type: "LOGIN",
      message: "Inicio de sesión exitoso (Admin)",
      ts: new Date().toISOString(),
    },
    // New Activity Feed Mock
    {
      type: "SALE",
      message: "Venta registrada #1024",
      amount: 45.0,
      user: "Juan",
      ts: new Date().toISOString(),
    },
    {
      type: "ADD_PRODUCT",
      message: "Producto agregado: Harina PAN",
      user: "Admin",
      ts: new Date(Date.now() - 3600000).toISOString(),
    },
    {
      type: "PAYMENT",
      message: "Pago recibido: Ana López",
      amount: 120.0,
      user: "Admin",
      ts: new Date(Date.now() - 7200000).toISOString(),
    },
    {
      type: "STOCK_LOW",
      message: "Stock bajo: Leche 1L",
      user: "System",
      ts: new Date(Date.now() - 86400000).toISOString(),
    },
  ],
  // New Orders (Encargos)
  orders: [
    {
      id: 1,
      client: "Carlos Pérez",
      product: "Caja de Aceite x12",
      status: "pending",
      date: new Date().toISOString(),
    },
    {
      id: 2,
      client: "María Rodriguez",
      product: "5 Sacos de Arroz",
      status: "ready",
      date: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      id: 3,
      client: "Pedro D.",
      product: "Queso Especial",
      status: "delivered",
      date: new Date(Date.now() - 172800000).toISOString(),
    },
  ],
  // Sales History for Chart (Last 7 days)
  salesHistory: Array.from({ length: 7 }, (_, i) => {
    const d = new Date();
    d.setDate(d.getDate() - (6 - i));
    return {
      date: d.toLocaleDateString("es-ES", { weekday: "short" }),
      sales: Math.floor(Math.random() * 500) + 100,
      payments: Math.floor(Math.random() * 400) + 50,
    };
  }),
  plans: [
    {
      id: 1,
      name: "🥉 Básico",
      price: 9.99,
      currency: "USD",
      features: ["Hasta 50 Productos", "1 Usuario", "Soporte Básico"],
      status: "active",
    },
    {
      id: 2,
      name: "🥈 Profesional",
      price: 29.99,
      currency: "USD",
      features: [
        "Hasta 500 Productos",
        "5 Usuarios",
        "Facturación",
        "Soporte Prioritario",
      ],
      status: "active",
    },
    {
      id: 3,
      name: "🥇 Premium",
      price: 99.99,
      currency: "USD",
      features: [
        "Productos Ilimitados",
        "Usuarios Ilimitados",
        "API Access",
        "Soporte 24/7",
      ],
      status: "active",
    },
  ],
  // New mock collections for extended settings
  sessions: [
    {
      id: 1,
      device: "Chrome / Windows",
      ip: "192.168.1.1",
      location: "Caracas, VE",
      lastActive: new Date().toISOString(),
      current: true,
    },
    {
      id: 2,
      device: "Safari / iPhone",
      ip: "201.21.10.5",
      location: "Maracaibo, VE",
      lastActive: new Date(Date.now() - 3600000 * 2).toISOString(),
      current: false,
    },
  ],
  notifications: {
    admin: { userExpiring: true, userSuspended: true },
    user: { closeCutoff: true, suspended: true },
    channels: { system: true, email: false },
  },
  supportMessages: [
    {
      id: 1,
      user: "vendedor",
      subject: "Problema con impresora",
      text: "No puedo imprimir el ticket de venta #1024",
      date: new Date(Date.now() - 7200000).toISOString(),
      read: false,
    },
    {
      id: 2,
      user: "vendedor",
      subject: "Duda sobre cierre",
      text: "¿A qué hora se debe hacer el cierre hoy?",
      date: new Date(Date.now() - 86400000 * 2).toISOString(),
      read: true,
    },
  ],
  auditLogs: [
    {
      id: 1,
      action: "CREATE_USER",
      detail: 'Creó usuario "vendedor2"',
      admin: "admin",
      date: new Date(Date.now() - 86400000 * 5).toISOString(),
    },
    {
      id: 2,
      action: "UPDATE_SETTINGS",
      detail: "Cambió moneda a USD",
      admin: "admin",
      date: new Date(Date.now() - 86400000 * 10).toISOString(),
    },
  ],
  systemConfig: {
    currency: "USD",
    symbol: "$",
    taxCookies: true,
    taxRate: 16,
    themeColor: "#2563eb",
    dateFormat: "DD/MM/YYYY",
    timezone: "America/Caracas",
    limits: { maxProducts: 500, maxClients: 100 }, // per user default
  },
};
